GET http://localhost:3000/

### get all containers
GET http://localhost:3000/api/containers

### get single container
GET http://localhost:3000/api/containers/2

###
GET https://jsonplaceholder.typicode.com/users

### Create Post
POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json

{
    "containerId": 50,
    "container title": "new container",
    "in container": "boxes in container"
}